# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('button', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('imagepath', models.FilePathField()),
            ],
        ),
    ]
