# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefrontend', '0002_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.CharField(default='default-slug', max_length=20),
        ),
    ]
