# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefrontend', '0004_auto_20170725_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
        migrations.AddField(
            model_name='products',
            name='slugg',
            field=models.SlugField(default='default-slug', max_length=20),
            preserve_default=False,
        ),
    ]
